# Site settings
title: Florin Bidian's Blog
home: Blog
header-img: img/distributed.jpg
description: ""
baseurl: ""
url: "http://bidianf.github.io"
resume: true
github_username:  bidianf
linkedin_username: florin-bidian

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins:
  - jekyll-sitemap
  - jekyll-paginate
