project:
  type: website
  output-dir: docs

website:
  title: "Florin Bidian"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - posts.qmd
      - research.qmd

format:
  html:
    theme: 
      light: cosmo
      dark: solar
    css: styles.css
    toc: true
    page-layout: full





