---
title: "Research"
---

You can access my academic research papers [here](https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=1843987).

___

I refereed for [Econometrica](https://onlinelibrary.wiley.com/journal/14680262), [Journal of Economic Theory](https://www.sciencedirect.com/journal/journal-of-economic-theory), [Journal of Mathematical Economics](https://www.sciencedirect.com/journal/journal-of-mathematical-economics), [Economic Theory](https://www.springer.com/journal/199), [Journal of Empirical Finance](https://www.sciencedirect.com/journal/journal-of-empirical-finance), [Review of Financial Economics](https://onlinelibrary.wiley.com/journal/18735924), [Optimization](https://www.tandfonline.com/journals/gopt20).

___

I presented my research at: 

[SAET Faro, PT](https://saet.uiowa.edu/past-events/saet2017/), [EWGET Salamanca, ES](https://eventos.usal.es/event_detail/7594/detail.html), [Georgia State University](gsu.edu) (2017),
[University of Tokyo](https://www.u-tokyo.ac.jp/en/), [Bank of Japan Tokyo, JP](https://www.boj.or.jp/en/), XXV EWGET Glasgow, GB, [INFER Reus, ES](https://infer-research.eu/wp-content/uploads/2020/12/Call-for-Papers-INFER-Conference-2016.pdf), [ERMAS Timisoara, RO](https://ermas2016.uvt.ro), [GEBA Iasi, RO](https://www.feaa.uaic.ro/geba/2016/Programme.html) (2016), [ERMAS Cluj, RO](https://econ.ubbcluj.ro/ermas2015/) (2015), EEA-ESEM Toulouse, FR,  [ERMAS Cluj, RO](https://econ.ubbcluj.ro/ermas2014/), [INFER Timisoara, RO](https://infer-research.eu/wp-content/uploads/2020/12/Call-for-papers_INFER-Workshop-Timisoara-2014.pdf) (2014), [Brown University](brown.edu), [Yeshiva University](yu.edu), [AMES SG](https://ames2023.webflow.io), China Meetings of the Econometric Society Beijing, CN, [XXII EWGET Vienna, AT](https://ewget2013.univie.ac.at), [MBF Rome, IT](https://economiaefinanza.luiss.it/news/2013/06/18/xxii-international-conference-money-banking-and-finance) (2013), 
[LAMES Lima, PE](https://www.up.edu.pe/lacealames/home.aspx), [NASM Evanston, US](https://www.econometricsociety.org/uploads/regions/program_nasm_2012.pdf), XXI EWGET Exeter, UK (2012), [Utah State University](usu.edu), [SAET Faro, PT](http://saet.uiowa.edu/past-events/saet2011/), [Georgia State University](gsu.edu) (2011)